import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { carlito, inter } from "../app/ui/fonts";
import { ToastProvider } from "../components/providers/ToastProvider";
import { NotificationProvider } from "../components/providers/NotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <ToastProvider>
          <NotificationProvider>
            {children}
          </NotificationProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
